### PR TITLE
Conversion to Swift 5

### PR DESCRIPTION
**Pull request by antoinelamy**
- All the content from @bpisano-luna PR
- Remove the added SWIFT_VERSION build setting in project file
- Run Swift 5 tests on Xcode 10.2
- Change `swift_version` in podspec

### CODE REVIEW

**Comment by antoinelamy** [comment]
Will there finally be a Swift 5 release? 🤞

**Comment by antoinelamy** [comment]
@nlutsenko all good?

**Comment by mbientlab** [comment]
Hey team, would you kindly update to swift 5? If you need any support, let us know!

**Comment by nlutsenko** [comment]
Hey guys, sorry, it's been a while.
Let me look into making it happen today.
Should have a new release by end of this weekend.
Thank you for your patience ;)

**Comment by mbientlab** [comment]
You rock! I've been waiting for this and I'm super stoked. Thanks Nikita!

**Comment by nlutsenko** [comment]
New release is coming tomorrow morning.
Also going to include SwiftPM support.

**Pull request closed without merging**
