### PR TITLE
Swift 4.0 Support

### LINKED ISSUE #59: 13 Issues on XCode 9 / iOS 11
Semantic issues. When is a release planed?

### LINKED ISSUE #61: Swift 4 update
Hi, @nlutsenko. Are you planning to deploy an update for swift4? Have some troubles and getting a swift compile error.

### PR DESCRIPTION
**Pull request by nlutsenko**
Includes all the changes required to support Swift 4.0
Also cleans up tests, since it's finally possible with Swift 4.

Superseds and closes #62 
Fixes #59 
Fixes #61

### CODE REVIEW

**Comment by nlutsenko** [comment]
Hey @akwilliamson, sorry I took over your Pull Request #62.
Would appreciate your eyes and review on this.

This is about the same amount of changes for the core library, but also includes changes to enable warnings introduced in Xcode 9 and  fully fix all the warnings introduced in Swift 4.
It also adds some cosmetic nice things on top 🍰

**Review by akwilliamson — COMMENTED** [review]
`currentTestName` is still defined and used elsewhere. Should it be removed entirely? Regardless, the comment about Swift 2.1 ~> Swift 2.2 is outdated in the `Tests/XCTestCase+TestName.swift` where `currentTestName` is defined.

**Comment by akwilliamson** [comment]
Looks good to me.

**Comment by flovilmart** [comment]
👍 thanks !

**Pull request merged**
